version: '3.7'   # docker-compose version
services:
  angular: #angularApp
   container_name: angularappdocker
   build: '/home/shailendra/newfolder/SimpleMEANappwithMongoExpress/angular'
   ports:
     - "4200:4200"

  nodejs: #nodejsapp
   container_name: nodejsappdocker
   build: '/home/shailendra/newfolder/SimpleMEANappwithMongoExpress/dockerizedNode'
   ports:
     - "3000:3000"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example


  server: #webserver
   container_name: nginxdocker
   image: nginx
   ports:
     - "80:80"
